import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import {
  ClerkProvider
} from '@clerk/nextjs'
import { dark, neobrutalism } from '@clerk/themes'
import Header from "../components/header";

export const metadata = {
  title: "AI Career",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${inter.className}`}
        >
          <Header />
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <main className="min-h-screen">
              {children}
            </main>
          </ThemeProvider>
          <footer className="bg-black text-white text-center">
            Made with love :)
          </footer>
        </body>

      </html>
    </ClerkProvider>

  );
}
